- hosts: haproxy
  tasks:
    - name: Installs haproxy load balancer
      apt: pkg=haproxy state=latest update_cache=yes

    - name: Pushes configuration
      template: src=/root/templates/haproxy.cfg dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
      notify:
        - restart haproxy

    - name: Sets default starting flag to 1
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
      notify:
        - restart haproxy

    - name: Enable service haproxy
      systemd:
        name: haproxy
        enabled: yes


  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted

